lane :upload_ipa do
  upload_to_testflight(
    ipa: "../build/humake_touch.ipa",
    api_key: app_store_connect_api_key(
      key_id: ENV["APP_STORE_KEY_ID"],
      issuer_id: ENV["FASTLANE_ISSUER_ID"],
      key_filepath: File.expand_path("AuthKey.p8", __dir__),
      in_house: false
    ),
    skip_waiting_for_build_processing: true
  )
end
